### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by zeritonius** [grucloud/bau#20]
What is the license for this repository, please?

Thank you.

**Comment by FredericHeem** [comment]
Thanks for your feedback, the BSD license has been added, closed in https://github.com/grucloud/bau/pull/22

**Comment by zeritonius** [comment]
> the BSD license has been added
I'm not sure I got this part. 
https://github.com/grucloud/bau/blob/main/LICENSE lists the license as MIT, not BSD. Which one is, please?

**Comment by FredericHeem** [comment]
Sorry, I meant MIT
